version: '3.8'

services:
    plasticscm:
        image: gmhaw/plasticscm-server-netcore:latest
        container_name: plasticscm
        restart: unless-stopped
        command: -v start # Must be configured interactively once using 'config' when no config files and license are provided
        expose:
            - '7179' # Webadmin HTTPS port
            - '8088' # Plastic SSL port
        volumes:
            - type: volume
              source: config
              target: '/conf/'
            - type: volume
              source: db
              target: '/db/jet'
            - type: volume
              source: logs
              target: '/logs'
        labels:
            - traefik.enable=true
            # Plastic VCS Service (SSL)
            - traefik.tcp.routers.plastic.rule=HostSNI(`plastic.mycompany.com`)
            - traefik.tcp.routers.plastic.entrypoints=plastic #8088
            - traefik.tcp.routers.plastic.service=plastic
            - traefik.tcp.routers.plastic.tls=true
            - traefik.tcp.routers.plastic.tls.passthrough=true
            - traefik.tcp.services.plastic.loadbalancer.server.port=8088 # SSL connection
            # Plastic Webadmin (HTTPS)
            - traefik.tcp.routers.plasticweb.rule=HostSNI(`plastic.mycompany.com`)
            - traefik.tcp.routers.plasticweb.entrypoints=websecure #443
            - traefik.tcp.routers.plasticweb.service=plastic-webadmin
            - traefik.tcp.routers.plasticweb.tls=true
            - traefik.tcp.routers.plasticweb.tls.passthrough=true
            - traefik.tcp.services.plastic-webadmin.loadbalancer.server.port=7179 # HTTPS connection

volumes:
   config:
       name: plasticscm_config
   db:
       name: plasticscm_db
   logs:
       name: plasticscm_logs
