version: '3.8'

services:
    plasticscm:
        image: gmhaw/plasticscm-server-netcore:latest
        container_name: plasticscm
        restart: unless-stopped
        command: -v start # Must be configured interactively once using 'config' when no config files and license are provided
        expose:
            - '7179' # Webadmin HTTPS port
            - '8088' # Plastic SSL port
        volumes:
            - type: volume
              source: config
              target: '/conf/'
            - type: volume
              source: db
              target: '/db/jet'
            - type: volume
              source: logs
              target: '/logs'
            # bind the certificate into the plastiscm server directory; Will be overwritten from time to time
            - type: bind
              source: './certs/plastic.mycompany.com.pfx'
              target: '/opt/plasticscm5/server/plastic.mycompany.com.pfx'
        labels:
            - traefik.enable=true
            # Plastic VCS Service (SSL)
            - traefik.tcp.routers.plastic.rule=HostSNI(`plastic.mycompany.com`)
            - traefik.tcp.routers.plastic.entrypoints=plastic #8088
            - traefik.tcp.routers.plastic.service=plastic
            - traefik.tcp.routers.plastic.tls=true
            - traefik.tcp.routers.plastic.tls.passthrough=true
            - traefik.tcp.services.plastic.loadbalancer.server.port=8088 # SSL connection
            # Plastic Webadmin (HTTPS)
            - traefik.tcp.routers.plasticweb.rule=HostSNI(`plastic.mycompany.com`)
            - traefik.tcp.routers.plasticweb.entrypoints=websecure #443
            - traefik.tcp.routers.plasticweb.service=plastic-webadmin
            - traefik.tcp.routers.plasticweb.tls=true
            - traefik.tcp.routers.plasticweb.tls.passthrough=true
            - traefik.tcp.services.plastic-webadmin.loadbalancer.server.port=7179 # HTTPS connection
    
    traefik-certs-dumper:
        image: ldez/traefik-certs-dumper:latest
        container_name: traefik-certs-dumper
        entrypoint: sh -c '
          apk add jq openssl
          ; while ! [ -e /data/acme.json ]
          || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
          sleep 1
          ; done
          && traefik-certs-dumper file --version v2 --watch
          --source /data/acme.json --dest /data/certs --domain-subdir=true --crt-ext=.pem
          --post-hook "sh post_hook.sh"'
        volumes:
            # location of acme.json created by traefik; All certs will also dumped in here
            - type: bind
              source: '../traefik/letsencrypt/'
              target: '/data/'
            - type: bind
              source: './create_pfx.sh'
              target: '/post_hook.sh'
            # target location for the created .pfx certificates; Also bound in the plasticscm service
            - type: bind
              source: './certs/'
              target: '/certs/'

volumes:
   config:
       name: plasticscm_config
   db:
       name: plasticscm_db
   logs:
       name: plasticscm_logs
